name: Setup Free RDP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install XFCE and XRDP
        run: |
          sudo apt-get update
          sudo apt-get install -y xfce4 xfce4-goodies xrdp
          echo xfce4-session >~/.xsession
          sudo systemctl enable xrdp
          sudo systemctl start xrdp

      - name: Open RDP Port (Firewall)
        run: |
          sudo ufw allow 3389/tcp
          sudo ufw enable

      - name: Restart XRDP Service
        run: |
          sudo systemctl restart xrdp
          sudo systemctl status xrdp --no-pager

      - name: Run Ngrok Tunnel
        env:
          NGROK_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        run: |
          ngrok authtoken $NGROK_TOKEN
          nohup ngrok tcp 3389 > ngrok.log 2>&1 &

      - name: Wait for Ngrok to Start
        run: sleep 10

      - name: Debug Ngrok Status
        run: |
          ps aux | grep ngrok
          cat ngrok.log || echo "Ngrok log not found"

      - name: Output RDP Address
        run: |
          echo "Your RDP Address:"
          curl -s http://127.0.0.1:4040/api/tunnels | jq '.tunnels[0].public_url'
